### ISSUE TITLE
Save failure on Ubuntu with tiddlywiki classic

### ISSUE THREAD

**Issue by wwood** [Jermolene/TiddlyDesktop#113]
Hi,
I'm getting failed to save errors when trying to save a classic wiki (been doing this a while..). Are classic wikis supported by TiddlyDesktop 0.0.9?

Looking at the chrome dev console:
```
Failed to load resource: net::ERR_FILE_NOT_FOUND

/home/ben/bioinfo/TiddlyDesktop-linux64-v0.0.9/js/wiki-file-window.js:97 Uncaught TypeError: Failed to execute 'observe' on 'MutationObserver': parameter 1 is not of type 'Node'.
    at WikiFileWindow.onloadiframe (/home/ben/bioinfo/TiddlyDesktop-linux64-v0.0.9/js/wiki-file-window.js:97:23)

(3) VM534:35 Failed to load file:///home/ben/Dropbox/pd.doc/pd.html: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.
injectedLoadFile @ VM534:35
```
The final line of that log is repeated each time I attempt to save.

Additionally, I see the following on the terminal where I ran `nw`
```
$ ./nw
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
/home/ben/bioinfo/TiddlyDesktop-linux64-v0.0.9/js/wiki-file-window.js:97
	this.favIconObserver.observe(faviconLink,{attributes: true, childList: true, characterData: true});
	                     ^

TypeError: Failed to execute 'observe' on 'MutationObserver': parameter 1 is not of type 'Node'.
    at WikiFileWindow.onloadiframe (/home/ben/bioinfo/TiddlyDesktop-linux64-v0.0.9/js/wiki-file-window.js:97:23)
/home/ben/bioinfo/TiddlyDesktop-linux64-v0.0.9/js/wiki-file-window.js:97
	this.favIconObserver.observe(faviconLink,{attributes: true, childList: true, characterData: true});
	                     ^

TypeError: Failed to execute 'observe' on 'MutationObserver': parameter 1 is not of type 'Node'.
    at WikiFileWindow.onloadiframe (/home/ben/bioinfo/TiddlyDesktop-linux64-v0.0.9/js/wiki-file-window.js:97:23)
/home/ben/bioinfo/TiddlyDesktop-linux64-v0.0.9/js/wiki-file-window.js:97
	this.favIconObserver.observe(faviconLink,{attributes: true, childList: true, characterData: true});
	                     ^

TypeError: Failed to execute 'observe' on 'MutationObserver': parameter 1 is not of type 'Node'.
    at WikiFileWindow.onloadiframe (/home/ben/bioinfo/TiddlyDesktop-linux64-v0.0.9/js/wiki-file-window.js:97:23)
/home/ben/bioinfo/TiddlyDesktop-linux64-v0.0.9/js/wiki-file-window.js:97
	this.favIconObserver.observe(faviconLink,{attributes: true, childList: true, characterData: true});
	                     ^

TypeError: Failed to execute 'observe' on 'MutationObserver': parameter 1 is not of type 'Node'.
    at WikiFileWindow.onloadiframe (/home/ben/bioinfo/TiddlyDesktop-linux64-v0.0.9/js/wiki-file-window.js:97:23)
gio: javascript:///;: The specified location is not supported
gio: javascript:///;: The specified location is not supported
gio: javascript:///;: The specified location is not supported
```
Again that final line is repeated each time I attempt to save. However, the line appears after I click OK when the failed to save alert comes up, so I guess that it is not related.

Thanks. ben

**Comment by Jermolene** [comment]
I think this problem may be fixed with the new v0.0.10:

https://github.com/Jermolene/TiddlyDesktop/releases/tag/v0.0.10

Please let me know how you get on.
