### ISSUE TITLE
Ubuntu 16.04.3 LTS: Still unable to save

### ISSUE THREAD

**Issue by rumbero71** [Jermolene/TiddlyDesktop#135]
Tried to use 0.0.11 on Ubuntu 16.04.3 and I am still unable to save. I am getting the same error message as when using plain Chromium. FF is not an option since the working versions will be going away.
Error messages when opening my Tiddly:
ATTENTION: default value of option force_s3tc_enable overridden by environment.
[22130:22130:0121/172531.332501:ERROR:browser_main_loop.cc(295)] GLib-GObject: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
/home/markus/Downloads/TiddlyDesktop-linux64-v0.0.11/js/wiki-file-window.js:97
        this.favIconObserver.observe(faviconLink,{attributes: true, childList: true, characterData: true});
                             ^

TypeError: Failed to execute 'observe' on 'MutationObserver': parameter 1 is not of type 'Node'.
    at WikiFileWindow.onloadiframe (/home/markus/Downloads/TiddlyDesktop-linux64-v0.0.11/js/wiki-file-window.js:97:23)
/home/markus/Downloads/TiddlyDesktop-linux64-v0.0.11/js/wiki-file-window.js:97
        this.favIconObserver.observe(faviconLink,{attributes: true, childList: true, characterData: true});

TypeError: Failed to execute 'observe' on 'MutationObserver': parameter 1 is not of type 'Node'.
    at WikiFileWindow.onloadiframe (/home/markus/Downloads/TiddlyDesktop-linux64-v0.0.11/js/wiki-file-window.js:97:23)
/home/markus/Downloads/TiddlyDesktop-linux64-v0.0.11/js/wiki-file-window.js:97
        this.favIconObserver.observe(faviconLink,{attributes: true, childList: true, characterData: true});
                             ^
TypeError: Failed to execute 'observe' on 'MutationObserver': parameter 1 is not of type 'Node'.
    at WikiFileWindow.onloadiframe (/home/markus/Downloads/TiddlyDesktop-linux64-v0.0.11/js/wiki-file-window.js:97:23)
/home/markus/Downloads/TiddlyDesktop-linux64-v0.0.11/js/wiki-file-window.js:97
        this.favIconObserver.observe(faviconLink,{attributes: true, childList: true, characterData: true});
                             ^

TypeError: Failed to execute 'observe' on 'MutationObserver': parameter 1 is not of type 'Node'.
    at WikiFileWindow.onloadiframe (/home/markus/Downloads/TiddlyDesktop-linux64-v0.0.11/js/wiki-file-window.js:97:23)

There is some error message about "option force_s3tc_enable overridden by environment". WTF ?
No error messages though when trying to save. Instead, an empty Chromium window is popping up

**Comment by dgerod** [comment]
Maybe related to #105

**Comment by Jermolene** [comment]
Hi @dgerod @rumbero71 please could you try [release v0.0.12](https://github.com/Jermolene/TiddlyDesktop/releases/tag/v0.0.12)? I believe that this issue is fixed.

**Comment by phlummox** [comment]
I got the same error on Ubuntu 14.04.5. If I upgrade to use release 0.0.12:

* I can save using tiddlywiki version - 5.1.15
* I can also save using version 2.8.1 of TiddlyWiki Classic
* I am unable to save using mGSD version 3.1.9,  which uses version 2.6.5 of TiddlyWiki Classic: I get an "It's not possible to save changes. Possible reasons include: ..." error dialog.

**Comment by Jermolene** [comment]
Hi everyone - please can you try the latest v0.0.13 release:

https://github.com/Jermolene/TiddlyDesktop/releases/tag/v0.0.13

**Comment by phlummox** [comment]
Hi - works for me with all of the versions I mentioned (tiddlywiki, TiddlyWiki Classic and mGSD), on both Ubuntu 14.04.5, and Ubuntu 16.04.  Many thanks!

**Comment by Jermolene** [comment]
That's great @phlummox thanks for letting me know
